#+TITLE: Historical Timeline
/The web application allows to create timelines of historical events that
teachers can show to students to better learn history./

The main functionality for teachers is to add new historical events
(e.g. Austerlitz battle, Dec 2, 1805). Each event is represented by a date, a
location, a description and an image/placeholder. Teachers can create several
timelines and add events to them. All events on a timeline will be shown
graphically ordered in time (no need of something complex, also some simple HTML
will do it). Teachers can create some study groups (e.g. Roman Empire, Second
World War, etc...) and enroll students. Teachers can add one or more timelines
to each group. Students can login to the system and take part to some groups
created by teachers. They will be able to see all the timelines for the specific
group and add a comment to them. Searching among all events is also possible.
* How to build it
  Use the Maven wrapper to build the project:
  #+BEGIN_SRC sh
    ./mvnw clean install
  #+END_SRC

  The whole application can be then executed as follows:
  #+BEGIN_SRC sh
    cd timeline
    ../mvnw
  #+END_SRC

  The user interface is then accessible at =http://localhost:8080/pa165= and REST API at
  =http://localhost:8080/pa165/rest=. More information about the REST API is in [[./timeline-rest/README.org][this README]].

  The REST API and also the web application can be executed independently. For more information
  about this, visit the README of the corresponding module.
* Project structure
  The =historrical-timeline= project is split into following modules:
  - [[./timeline][=timeline=]] :: Module that merges =timeline-ui= and =timeline-rest= into one WAR.
  - [[./timeline-api][=timeline-api=]] :: Public API for =historical-timeline=.
  - [[./timeline-data][=timeline-data=]] :: Contains sample data for the project.
  - [[./timeline-persistence][=timeline-persistence=]] :: Module responsible for data persistence in the database.
  - [[./timeline-rest][=timeline-rest=]] :: REST interface for =historical-timeline=.
  - [[./timeline-service][=timeline-service=]] :: Implementation of public API and service logic.
  - [[./timeline-ui][=timeline-ui=]] :: Web application developed in /Angular/.
* Use-case diagram
  #+BEGIN_SRC plantuml :file images/use-case_diagram.svg :exports results
    left to right direction

    actor User
    actor Student
    actor Teacher

    User <|-- Student
    User <|-- Teacher

    User --> (login)
    User --> (logout)
    User --> (register)
    User --> (view timeline)
    User --> (view study group)

    Student --> (add comment to timeline)
    Student --> (search among all events)

    Teacher --> (create event)
    Teacher --> (create timeline)
    Teacher --> (create study group)
    Teacher --> (add event to timeline)
    Teacher --> (add timeline to study group)
    Teacher --> (enroll student to study group)
  #+END_SRC

  #+RESULTS:
  [[file:images/use-case_diagram.svg]]
* Class diagram
  #+BEGIN_SRC plantuml :file images/class_diagram.svg :exports results
    class HistoricalEvent {
      name: String
      description: String
      date: LocalDate
      location: String
      image: byte[]
    }

    class HistoricalTimeline {
      name: String
    }

    HistoricalTimeline "1" *-- "*" HistoricalEvent

    class StudyGroup {
      name: String
    }

    StudyGroup "1" *-- "*" HistoricalTimeline

    class User {
      isTeacher: Boolean
      firstName: String
      lastName: String
      username: String
      hashedPassword: String
    }

    User "*" o--o "*" StudyGroup

    class TimelineComment {
      text: String
    }

    HistoricalTimeline "1" *-- "*" TimelineComment
    TimelineComment "*" o-- "1" User
  #+END_SRC

  #+RESULTS:
  [[file:images/class_diagram.svg]]
